version: '3.8'

services:
  pg:
    image: postgres:17.4-alpine3.21
    environment:
      POSTGRES_DB: ${PG_NAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - bigtech-db-data:/var/lib/postgresql/data
volumes:
  bigtech-db-data: