name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  REGISTRY: "cr.selcloud.ru/bladforceone"
  IMAGE_NAME: "auth"
  CONTAINER_NAME: "auth-container"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Selectel Registry
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login cr.selcloud.ru -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          TAG_NAME=$(echo $GITHUB_SHA | head -c7)
          docker buildx build \
            --platform linux/amd64 \
            --push \
            --no-cache \
            --tag $REGISTRY/$IMAGE_NAME:$TAG_NAME \
            --tag $REGISTRY/$IMAGE_NAME:latest \
            -f Dockerfile .

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            TAG_NAME=$(echo $GITHUB_SHA | head -c7)
            FULL_IMAGE_NAME="$REGISTRY/$IMAGE_NAME:$TAG_NAME"
            
            # Login to registry
            echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login cr.selcloud.ru -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin
            
            # Stop and remove old container if exists
            docker stop $CONTAINER_NAME || true
            docker rm $CONTAINER_NAME || true
            
            # Pull new image and run
            docker pull $FULL_IMAGE_NAME
            docker run -d \
              -p 8080:8080 \
              --name $CONTAINER_NAME \
              --restart unless-stopped \
              $FULL_IMAGE_NAME
            
            # Cleanup old images
            docker image prune -af