name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  REGISTRY: "cr.selcloud.ru/bladforceone"
  IMAGE_NAME: "auth"
  CONTAINER_NAME: "auth-container"

jobs:
  image-build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Registry
        run: docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} $REGISTRY

      - name: Build and Push Docker Image
        run: |
          TAG_NAME=$(echo $GITHUB_SHA | head -c7)
          docker buildx create --use
          docker buildx build --no-cache --push --tag $REGISTRY/$IMAGE_NAME:$TAG_NAME -f Dockerfile .

  deploy-image:
    runs-on: ubuntu-latest
    needs: image-build-and-push

    steps:
      - name: Verify network
        run: |
          echo "Проверяем подключение к ${{ secrets.SERVER_HOST }}"
          ping -c 3 ${{ secrets.SERVER_HOST }} || echo "Ping failed"
          nc -zv ${{ secrets.SERVER_HOST }} 22 || echo "Port 22 unavailable"

      - name: Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT || '22' }}
          script: |
            # Устанавливаем переменные явно
            REGISTRY="cr.selcloud.ru/bladforceone"
            IMAGE_NAME="auth"
            CONTAINER_NAME="auth-container"
            TAG_NAME=$(echo $GITHUB_SHA | head -c7)
            FULL_IMAGE="$REGISTRY/$IMAGE_NAME:$TAG_NAME"

            # Безопасный вход в реестр
            echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login cr.selcloud.ru -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin

            # Останавливаем и удаляем контейнер (игнорируем ошибки если контейнера нет)
            docker stop $CONTAINER_NAME || true
            docker rm $CONTAINER_NAME || true

            # Запускаем новый контейнер
            docker run -d \
              -p 8080:8080 \
              --name $CONTAINER_NAME \
              --restart unless-stopped \
              $FULL_IMAGE

            # Очистка
            docker image prune -af